# Generated by Django 3.2.9 on 2021-12-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_auto_20211207_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchlist_app.streamplatform', to_field='name'),
        ),
    ]
